### ISSUE TITLE
Widget not working with flutter beta 1.24.0

### ISSUE THREAD

**Issue by cedteg** [hcbpassos/double_back_to_close_app#13]
Hey,

I get this issue with flutter beta
>double_back_to_close_app.dart:91:30: Error: No named parameter with the name 'nullOk'.
    if (Scaffold.of(context, nullOk: true) == null) {

**Comment by ch3ckmat3** [comment]
Came here to post this error

**Comment by ch3ckmat3** [comment]
Shall we paste the raw code in our App or shall we wait for the fix?

**Comment by ghost** [comment]
Thanks for letting me know.

This problem is caused by breaking changes on the flutter framework due to null safety support.

If I were to tight up sdk constraints in `pubspec.yaml` and fix the problem mentioned, the new release wouldn't be backward compatible, so I'll work around this by publishing a pre-release soon :)

**Comment by surveshoeb** [comment]
> Thanks for letting me know.
> 
> This problem is caused by breaking changes on the flutter framework due to null safety support.
> 
> If I were to tight up sdk constraints in `pubspec.yaml` and fix the problem mentioned, the new release wouldn't be backward compatible, so I'll work around this by publishing a pre-release soon :)

Will be waiting for your release.

**Comment by hcbpassos** [comment]
Prerelease [1.3.0-nullsafety.1](https://pub.dev/packages/double_back_to_close_app/versions/1.3.0-nullsafety.1) is available on pub :)
